// export const USER_CREATED = 'USER_CREATED';
// export const USERS_RECEIVED = 'USERS_RECEIVED';
// export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED';
// export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// export const GET_ERRORS = 'GET_ERRORS';
// export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const USER_CREATED = 'USER_CREATED';
export const USERS_RECEIVED = 'USERS_RECEIVED';
export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const FETCH_ALBUMS_PENDING = 'FETCH_ALBUMS_PENDING';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_ERROR = 'FETCH_ALBUMS_ERROR';

export const SET_ARTIST_IDS = 'SET_ARTIST_IDS';
export const FETCH_ARTISTS_PENDING = 'FETCH_ARTISTS_PENDING';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_ERROR = 'FETCH_ARTISTS_ERROR';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS';
export const FETCH_NEW_RELEASES_ERROR = 'FETCH_NEW_RELEASES_ERROR';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
export const FETCH_FEATURED_ERROR = 'FETCH_FEATURED_ERROR';

export const FETCH_PLAYLIST_MENU_PENDING = 'FETCH_PLAYLIST_MENU_PENDING';
export const FETCH_PLAYLIST_MENU_SUCCESS = 'FETCH_PLAYLIST_MENU_SUCCESS';
export const ADD_PLAYLIST_ITEM = 'ADD_PLAYLIST_ITEM';
export const FETCH_PLAYLIST_MENU_ERROR = 'FETCH_PLAYLIST_MENU_ERROR';

export const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE';
export const FETCH_SONGS_PENDING = 'FETCH_SONGS_PENDING';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_ERROR = 'FETCH_SONGS_ERROR';
export const SEARCH_SONGS_PENDING = 'SEARCH_SONGS_PENDING';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';
export const SEARCH_SONGS_ERROR = 'SEARCH_SONGS_ERROR';
export const FETCH_RECENTLY_PLAYED_PENDING = 'FETCH_RECENTLY_PLAYED_PENDING';
export const FETCH_RECENTLY_PLAYED_SUCCESS = 'FETCH_RECENTLY_PLAYED_SUCCESS';
export const FETCH_RECENTLY_PLAYED_ERROR = 'FETCH_RECENTLY_PLAYED_ERROR';
export const FETCH_PLAYLIST_SONGS_PENDING = 'FETCH_PLAYLIST_SONGS_PENDING';
export const FETCH_PLAYLIST_SONGS_SUCCESS = 'FETCH_PLAYLIST_SONGS_SUCCESS';
export const FETCH_PLAYLIST_SONGS_ERROR = 'FETCH_PLAYLIST_SONGS_ERROR';
export const FETCH_ARTIST_SONGS_PENDING = 'FETCH_ARTIST_SONGS_PENDING';
export const FETCH_ARTIST_SONGS_SUCCESS = 'FETCH_ARTIST_SONGS_SUCCESS';
export const FETCH_ARTIST_SONGS_ERROR = 'FETCH_ARTIST_SONGS_ERROR';
export const PLAY_SONG = 'PLAY_SONG';
export const STOP_SONG = 'STOP_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const RESUME_SONG = 'FETCH_ALBUMS_PENDING';
export const INCREASE_SONG_TIME = 'INCREASE_SONG_TIME';

export const UPDATE_VOLUME = 'UPDATE_VOLUME';

export const SET_TOKEN = 'SET_TOKEN';

export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const ADD_SONG_TO_LIBRARY_SUCCESS = 'ADD_SONG_TO_LIBRARY_SUCCESS';
export const ADD_SONG_TO_LIBRARY_ERROR = 'ADD_SONG_TO_LIBRARY_ERROR';
