export const USER_CREATED = 'USER_CREATED';
export const USERS_RECEIVED = 'USERS_RECEIVED';
export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
